### ISSUE TITLE
str_contains breaks the plugin for PHP versions lower than 8

### ISSUE THREAD

**Issue by EchterAgo** [newfold-labs/wp-plugin-mojo#21]
The code introduced in #18 uses [`str_contains`](https://www.php.net/manual/en/function.str-contains.php), which is only available in PHP 8, breaking any lower versions. `composer.json` indicates that PHP 7 is required.

**Comment by circlecube** [comment]
Thank you kindly for the alert @EchterAgo 

This has been fixed in the [2.0.2](https://github.com/newfold-labs/wp-plugin-mojo/releases/tag/2.0.2) release today. Also fixed in the legacy mojo [1.7.1](https://github.com/bluehost/mojo-marketplace-wp-plugin/releases/tag/1.7.1) release today.
